/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_jdpapi_DPAPI */

#ifndef _Included_net_sourceforge_jdpapi_DPAPI
#define _Included_net_sourceforge_jdpapi_DPAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sourceforge_jdpapi_DPAPI
 * Method:    CryptProtectData
 * Signature: (Ljava/lang/String;[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sourceforge_jdpapi_DPAPI_CryptProtectData
  (JNIEnv *, jclass, jstring, jbyteArray, jboolean);

/*
 * Class:     net_sourceforge_jdpapi_DPAPI
 * Method:    CryptUnprotectData
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sourceforge_jdpapi_DPAPI_CryptUnprotectData
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     net_sourceforge_jdpapi_DPAPI
 * Method:    CryptUnprotectDataBinary
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sourceforge_jdpapi_DPAPI_CryptUnprotectDataBinary
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     net_sourceforge_jdpapi_DPAPI
 * Method:    CryptProtectDataBinary
 * Signature: ([B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sourceforge_jdpapi_DPAPI_CryptProtectDataBinary
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
